// generated by make_web.py -- do not edit
window.STUDY_MANIFEST = {
  "question": "Which row of images do you prefer?",
  "models": [
    {
      "key": "m1",
      "col": "R3GAN2"
    },
    {
      "key": "m2",
      "col": "GAT-XL-2"
    },
    {
      "key": "m3",
      "col": "IMF-XL-2"
    }
  ],
  "pairs": [
    [
      0,
      1
    ],
    [
      0,
      2
    ],
    [
      1,
      2
    ]
  ],
  "classes": [
    {
      "class_id": "12",
      "label": "bird",
      "file": "12.webp",
      "src": {
        "m1": "00_12_bird.png",
        "m2": "00_12_bird.png",
        "m3": "00_12_bird.png"
      }
    },
    {
      "class_id": "738",
      "label": "pot",
      "file": "738.webp",
      "src": {
        "m1": "01_738_pot.png",
        "m2": "01_738_pot.png",
        "m3": "01_738_pot.png"
      }
    },
    {
      "class_id": "975",
      "label": "lakeside",
      "file": "975.webp",
      "src": {
        "m1": "02_975_lakeside.png",
        "m2": "02_975_lakeside.png",
        "m3": "02_975_lakeside.png"
      }
    },
    {
      "class_id": "437",
      "label": "beacon",
      "file": "437.webp",
      "src": {
        "m1": "03_437_beacon.png",
        "m2": "03_437_beacon.png",
        "m3": "03_437_beacon.png"
      }
    },
    {
      "class_id": "387",
      "label": "red panda",
      "file": "387.webp",
      "src": {
        "m1": "04_387_red_panda.png",
        "m2": "04_387_red_panda.png",
        "m3": "04_387_red_panda.png"
      }
    },
    {
      "class_id": "289",
      "label": "snow leopard",
      "file": "289.webp",
      "src": {
        "m1": "05_289_snow_leopard.png",
        "m2": "05_289_snow_leopard.png",
        "m3": "05_289_snow_leopard.png"
      }
    },
    {
      "class_id": "562",
      "label": "fountain",
      "file": "562.webp",
      "src": {
        "m1": "06_562_fountain.png",
        "m2": "06_562_fountain.png",
        "m3": "06_562_fountain.png"
      }
    },
    {
      "class_id": "698",
      "label": "palace",
      "file": "698.webp",
      "src": {
        "m1": "07_698_palace.png",
        "m2": "07_698_palace.png",
        "m3": "07_698_palace.png"
      }
    },
    {
      "class_id": "14",
      "label": "indigo hunting",
      "file": "14.webp",
      "src": {
        "m1": "08_14_indigo_hunting.png",
        "m2": "08_14_indigo_hunting.png",
        "m3": "08_14_indigo_hunting.png"
      }
    },
    {
      "class_id": "291",
      "label": "lion",
      "file": "291.webp",
      "src": {
        "m1": "09_291_lion.png",
        "m2": "09_291_lion.png",
        "m3": "09_291_lion.png"
      }
    }
  ]
};
